# Generated by Django 5.1.6 on 2025-04-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_patientreport_doctor_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='chest_pain',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chronic_cough',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='exposure_to_pollutants',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fatigue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hemoptysis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='history_of_respiratory_diseases',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smoking_history',
        ),
    ]
