# Generated by Django 5.1.6 on 2025-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_patient_chest_pain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='severity_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
