# Generated by Django 5.1.6 on 2025-04-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_patientreport_severity_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientreport",
            name="severity_stage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
